version: "3"
services:
  app:
    image: kburk1997/relieveme
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=RelieveMe
